filebeat.config:
  strict.perms: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/cowrie/cowrie.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  pipeline: "cowrie-geoip"

setup.kibana:
  host: "http://kibana:5601"